version: '3.8'

services:
    redis:
        image: redis:alpine
        ports:
            - '6379:6379'

    app:
        build:
            context: .
        ports:
            - '8080:8080'
        environment:
            REDIS_ADDR: redis:6379
            IP_RATE_LIMIT: 1
            TOKEN_RATE_LIMIT: 3
            BLOCK_DURATION: 300
        depends_on:
            - redis
